version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      python-deps:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /amcl-share-backend
    schedule:
      interval: weekly
